# Generated by Django 4.2.30 on 2026-06-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_field', models.CharField(choices=[('person_name', '人物姓名'), ('person_relation', '亲属关系'), ('photo_date', '拍摄时间'), ('photo_location', '拍摄地点'), ('photo_people', '照片人物'), ('memory_content', '回忆内容'), ('other', '其他信息')], default='other', max_length=30, verbose_name='冲突字段')),
                ('version_a', models.TextField(verbose_name='版本A（原版本）')),
                ('version_a_author', models.CharField(default='', max_length=100, verbose_name='版本A提交人')),
                ('version_b', models.TextField(verbose_name='版本B（新版本）')),
                ('version_b_author', models.CharField(default='', max_length=100, verbose_name='版本B提交人')),
                ('description', models.TextField(blank=True, verbose_name='冲突说明')),
                ('status', models.CharField(choices=[('open', '待确认'), ('resolved', '已确认'), ('rejected', '已驳回')], default='open', max_length=20, verbose_name='处理状态')),
                ('resolved_version', models.CharField(blank=True, choices=[('A', '版本A'), ('B', '版本B')], max_length=1, null=True, verbose_name='最终版本')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='确认人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'db_table': 'conflict_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='出生年份')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='逝世年份')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='出生地')),
                ('description', models.TextField(blank=True, verbose_name='人物简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('status', models.CharField(choices=[('confirmed', '已确认'), ('pending', '待确认'), ('conflicted', '信息冲突')], default='pending', max_length=20, verbose_name='确认状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(default='家属', max_length=50, verbose_name='创建人')),
            ],
            options={
                'db_table': 'person',
                'ordering': ['birth_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='照片标题')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='照片文件')),
                ('era', models.CharField(choices=[('1920s', '1920年代'), ('1930s', '1930年代'), ('1940s', '1940年代'), ('1950s', '1950年代'), ('1960s', '1960年代'), ('1970s', '1970年代'), ('1980s', '1980年代'), ('1990s', '1990年代'), ('2000s', '2000年代'), ('2010s', '2010年代'), ('2020s', '2020年代'), ('unknown', '年代不详')], default='unknown', max_length=20, verbose_name='年代')),
                ('scene', models.CharField(choices=[('family_portrait', '全家福'), ('wedding', '婚礼'), ('daily_life', '日常生活'), ('festival', '节庆聚会'), ('travel', '旅行出游'), ('work_school', '工作/求学'), ('childhood', '童年'), ('military', '军旅'), ('funeral', '丧葬/纪念'), ('other', '其他')], default='other', max_length=30, verbose_name='场景')),
                ('source', models.CharField(choices=[('old_album', '老相册'), ('family_donation', '家人捐赠'), ('scanned', '扫描翻拍'), ('digital_camera', '数码相机'), ('phone', '手机拍摄'), ('social_media', '社交媒体'), ('other', '其他来源')], default='old_album', max_length=30, verbose_name='来源')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='拍摄地点')),
                ('taken_year', models.IntegerField(blank=True, null=True, verbose_name='拍摄年份')),
                ('description', models.TextField(blank=True, help_text='老人口述的事件背景', verbose_name='事件背景描述')),
                ('status', models.CharField(choices=[('archived', '已归档'), ('annotating', '补注中'), ('completed', '补注完成')], default='archived', max_length=20, verbose_name='补注状态')),
                ('uploader', models.CharField(default='家属', max_length=50, verbose_name='上传人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'photo',
                'ordering': ['-taken_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('father', '父亲'), ('mother', '母亲'), ('spouse', '配偶'), ('child', '子女'), ('sibling', '兄弟姐妹'), ('grandparent', '祖父母'), ('grandchild', '孙辈'), ('uncle_aunt', '叔伯/姑姨'), ('nephew_niece', '侄/甥'), ('cousin', '堂/表亲'), ('in_law', '姻亲'), ('other', '其他')], max_length=20, verbose_name='关系类型')),
                ('relation_note', models.CharField(blank=True, help_text='详细说明，如：大舅、二伯母等', max_length=300, verbose_name='关系备注')),
                ('added_by', models.CharField(default='家属', max_length=50, verbose_name='补注人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='memories.person', verbose_name='人物A')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='memories.person', verbose_name='人物B')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='PersonInPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name_override', models.CharField(blank=True, help_text='人物未确认时填写', max_length=100, verbose_name='暂用名/待确认名')),
                ('position_note', models.CharField(blank=True, help_text='如：前排左一、后排中间等', max_length=200, verbose_name='位置说明')),
                ('old_title', models.CharField(blank=True, help_text='拍摄时的称呼，如：小妹、阿强等', max_length=100, verbose_name='当时称呼')),
                ('role_note', models.CharField(blank=True, max_length=300, verbose_name='角色/状态备注')),
                ('added_by', models.CharField(default='家属', max_length=50, verbose_name='标注人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='标注时间')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='memories.person', verbose_name='关联人物')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_in_photo', to='memories.photo', verbose_name='照片')),
            ],
            options={
                'db_table': 'person_in_photo',
            },
        ),
        migrations.CreateModel(
            name='MigrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=200, verbose_name='迁出地')),
                ('to_place', models.CharField(max_length=200, verbose_name='迁入地')),
                ('move_year', models.IntegerField(blank=True, null=True, verbose_name='迁居年份')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='迁居原因')),
                ('added_by', models.CharField(default='晚辈', max_length=50, verbose_name='补注人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='memories.person', verbose_name='所属人物')),
            ],
            options={
                'db_table': 'migration_info',
                'ordering': ['move_year'],
            },
        ),
        migrations.CreateModel(
            name='MemoryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='回忆标题')),
                ('content', models.TextField(verbose_name='回忆内容')),
                ('occur_year', models.IntegerField(blank=True, null=True, verbose_name='发生年份')),
                ('occur_place', models.CharField(blank=True, max_length=300, verbose_name='发生地点')),
                ('author', models.CharField(default='家属', max_length=100, verbose_name='回忆讲述/撰写人')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待整理'), ('published', '已沉淀'), ('conflicted', '内容冲突')], default='draft', max_length=20, verbose_name='整理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_people', models.ManyToManyField(blank=True, related_name='memories', to='memories.person', verbose_name='关联人物')),
                ('related_photos', models.ManyToManyField(blank=True, related_name='memories', to='memories.photo', verbose_name='关联照片')),
            ],
            options={
                'db_table': 'memory_fragment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_type', models.CharField(choices=[('person', '人物信息'), ('relation', '亲属关系'), ('photo_info', '照片信息'), ('photo_person', '照片人物'), ('memory', '回忆内容'), ('conflict', '冲突版本')], max_length=20, verbose_name='确认类型')),
                ('title', models.CharField(max_length=300, verbose_name='确认事项')),
                ('detail', models.TextField(verbose_name='详细内容')),
                ('proposer', models.CharField(default='家属', max_length=100, verbose_name='提案人')),
                ('status', models.CharField(choices=[('pending', '待投票'), ('approved', '已通过'), ('rejected', '已否决'), ('tied', '平票待议')], default='pending', max_length=20, verbose_name='确认状态')),
                ('vote_approve', models.IntegerField(default=0, verbose_name='赞成票')),
                ('vote_reject', models.IntegerField(default=0, verbose_name='反对票')),
                ('voters', models.JSONField(blank=True, default=list, verbose_name='投票人列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('related_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='memories.conflictversion')),
                ('related_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='memories.memoryfragment')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='memories.person')),
                ('related_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='memories.photo')),
            ],
            options={
                'db_table': 'family_confirmation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conflictversion',
            name='related_memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='memories.memoryfragment', verbose_name='关联回忆'),
        ),
        migrations.AddField(
            model_name='conflictversion',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='memories.person', verbose_name='关联人物'),
        ),
        migrations.AddField(
            model_name='conflictversion',
            name='related_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='memories.photo', verbose_name='关联照片'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=100, verbose_name='别名/昵称')),
                ('usage_context', models.CharField(blank=True, help_text='如：乳名、旧时称呼、工作用名等', max_length=200, verbose_name='使用场景')),
                ('added_by', models.CharField(default='晚辈', max_length=50, verbose_name='补注人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='memories.person', verbose_name='所属人物')),
            ],
            options={
                'db_table': 'alias',
            },
        ),
    ]
