# Generated by Django 4.2.30 on 2026-06-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('identity_confirm', '人物身份确认'), ('old_name_supplement', '旧称/别名补充'), ('migration_supplement', '迁居信息补充'), ('event_narration', '事件背景口述'), ('relation_verify', '亲属关系校验')], max_length=30, verbose_name='任务类型')),
                ('title', models.CharField(max_length=300, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('source_type', models.CharField(choices=[('photo', '照片'), ('person', '人物'), ('memory', '回忆片段')], max_length=20, verbose_name='来源类型')),
                ('extra_context', models.JSONField(blank=True, default=dict, help_text='如位置信息、人物ID等', verbose_name='补充上下文')),
                ('assign_type', models.CharField(choices=[('family', '全家开放'), ('specific', '指定人员')], default='family', max_length=20, verbose_name='分派方式')),
                ('assigned_to', models.CharField(blank=True, help_text='指定家属时填写姓名', max_length=100, verbose_name='分派对象')),
                ('claimed_by', models.CharField(blank=True, max_length=100, verbose_name='认领人')),
                ('status', models.CharField(choices=[('open', '待认领'), ('assigned', '已分派待完成'), ('in_progress', '处理中'), ('submitted', '待审核'), ('completed', '已完成'), ('rejected', '已驳回'), ('conflicted', '进入确认台')], default='open', max_length=20, verbose_name='任务状态')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高', verbose_name='优先级')),
                ('created_by', models.CharField(default='系统', max_length=100, verbose_name='创建人')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='认领时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='memories.memoryfragment')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='memories.person')),
                ('related_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='memories.photo')),
            ],
            options={
                'db_table': 'collection_task',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=100, verbose_name='提交人')),
                ('submission_data', models.JSONField(default=dict, help_text='根据任务类型存储不同结构的数据', verbose_name='提交内容数据')),
                ('submission_text', models.TextField(blank=True, help_text='口述或长文本内容', verbose_name='文本内容')),
                ('has_conflict', models.BooleanField(default=False, verbose_name='是否有冲突')),
                ('conflict_description', models.TextField(blank=True, verbose_name='冲突说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('conflicted', '进入确认台')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reviewer', models.CharField(blank=True, max_length=100, verbose_name='审核人')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('related_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='memories.familyconfirmation')),
                ('related_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='memories.conflictversion')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='memories.collectiontask', verbose_name='所属任务')),
            ],
            options={
                'db_table': 'task_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.CharField(max_length=100, verbose_name='贡献人')),
                ('contribution_type', models.CharField(choices=[('task_submit', '任务提交'), ('task_claim', '任务认领'), ('task_approved', '任务审核通过'), ('clue_claim', '线索认领'), ('person_add', '人物建档'), ('memory_add', '回忆添加'), ('photo_annotate', '照片补注'), ('review_pass', '审核通过'), ('vote_participate', '参与投票')], max_length=30, verbose_name='贡献类型')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='贡献描述')),
                ('points', models.IntegerField(default=10, verbose_name='贡献积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='memories.memoryfragment')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='memories.person')),
                ('related_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='memories.photo')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='memories.collectiontask')),
            ],
            options={
                'db_table': 'contribution',
                'ordering': ['-created_at'],
            },
        ),
    ]
