# Generated by Django 4.2.30 on 2026-06-18 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_collectiontask_tasksubmission_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=500, verbose_name='原始地点名称')),
                ('standardized_name', models.CharField(blank=True, max_length=500, verbose_name='标准化地点名称')),
                ('level', models.CharField(choices=[('country', '国家'), ('province', '省/直辖市'), ('city', '市'), ('district', '区/县'), ('town', '乡镇/街道'), ('village', '村/社区'), ('detail', '详细地址')], default='detail', max_length=20, verbose_name='地点层级')),
                ('country', models.CharField(blank=True, default='中国', max_length=100, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='省/直辖市')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='区/县')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='乡镇/街道')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='村/社区')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='详细地址')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('alias_names', models.JSONField(blank=True, default=list, verbose_name='别名列表')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已确认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'standardized_location',
                'ordering': ['province', 'city', 'district'],
            },
        ),
        migrations.CreateModel(
            name='TimelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('birth', '出生'), ('death', '逝世'), ('migration', '迁居'), ('photo', '照片拍摄'), ('memory', '回忆事件'), ('event', '重要事件'), ('task_result', '采集任务结果')], max_length=30, verbose_name='节点类型')),
                ('source_type', models.CharField(choices=[('migration_info', '迁居记录'), ('photo', '照片'), ('memory', '回忆片段'), ('person', '人物档案'), ('task_submission', '采集任务提交'), ('manual', '手动添加')], max_length=30, verbose_name='数据来源')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源记录ID')),
                ('title', models.CharField(max_length=300, verbose_name='节点标题')),
                ('description', models.TextField(blank=True, verbose_name='节点描述')),
                ('original_location', models.CharField(blank=True, max_length=500, verbose_name='原始地点')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='月份')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='日期')),
                ('decade', models.CharField(blank=True, help_text='如：1980s', max_length=20, verbose_name='年代')),
                ('year_unknown', models.BooleanField(default=False, verbose_name='年份未知')),
                ('status', models.CharField(choices=[('confirmed', '已确认（正式时间线）'), ('pending', '待确认'), ('conflicted', '存在冲突'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('conflict_field', models.CharField(choices=[('location', '地点冲突'), ('year', '年份冲突'), ('both', '地点+年份冲突'), ('none', '无冲突')], default='none', max_length=10, verbose_name='冲突类型')),
                ('conflict_version_group', models.CharField(blank=True, help_text='同一事件的冲突版本共用此ID', max_length=50, verbose_name='冲突版本组ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_by', models.CharField(default='系统', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes_from', to='memories.standardizedlocation', verbose_name='迁出地（迁居用）')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='memories.standardizedlocation', verbose_name='标准化地点')),
                ('related_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='memories.conflictversion', verbose_name='关联冲突版本')),
                ('related_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='memories.memoryfragment', verbose_name='关联回忆')),
                ('related_migration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='memories.migrationinfo', verbose_name='关联迁居记录')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_nodes', to='memories.person', verbose_name='关联人物')),
                ('related_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='memories.photo', verbose_name='关联照片')),
            ],
            options={
                'db_table': 'timeline_node',
                'ordering': ['-year', '-month', '-day', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='standardizedlocation',
            index=models.Index(fields=['original_name'], name='standardize_origina_8e7e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='standardizedlocation',
            index=models.Index(fields=['standardized_name'], name='standardize_standar_442608_idx'),
        ),
        migrations.AddIndex(
            model_name='standardizedlocation',
            index=models.Index(fields=['province', 'city'], name='standardize_provinc_9771e2_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinenode',
            index=models.Index(fields=['related_person', 'year'], name='timeline_no_related_886636_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinenode',
            index=models.Index(fields=['node_type', 'status'], name='timeline_no_node_ty_dd8aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinenode',
            index=models.Index(fields=['location'], name='timeline_no_locatio_86b0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinenode',
            index=models.Index(fields=['decade'], name='timeline_no_decade_5bc75f_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinenode',
            index=models.Index(fields=['conflict_version_group'], name='timeline_no_conflic_bbcb43_idx'),
        ),
    ]
