# Generated by Django 4.2.30 on 2026-06-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_standardizedlocation_timelinenode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontask',
            name='source_type',
            field=models.CharField(choices=[('photo', '照片'), ('person', '人物'), ('memory', '回忆片段'), ('artifact', '物件')], max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='task_type',
            field=models.CharField(choices=[('identity_confirm', '人物身份确认'), ('old_name_supplement', '旧称/别名补充'), ('migration_supplement', '迁居信息补充'), ('event_narration', '事件背景口述'), ('relation_verify', '亲属关系校验'), ('artifact_identify', '物件鉴定/识别'), ('artifact_story', '物件故事补注'), ('artifact_source', '物件来源考证'), ('artifact_era', '物件年代确认'), ('artifact_custodian', '物件保管人确认')], max_length=30, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='conflictversion',
            name='conflict_field',
            field=models.CharField(choices=[('person_name', '人物姓名'), ('person_relation', '亲属关系'), ('photo_date', '拍摄时间'), ('photo_location', '拍摄地点'), ('photo_people', '照片人物'), ('memory_content', '回忆内容'), ('artifact_info', '物件信息'), ('other', '其他信息')], default='other', max_length=30, verbose_name='冲突字段'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('task_submit', '任务提交'), ('task_claim', '任务认领'), ('task_approved', '任务审核通过'), ('clue_claim', '线索认领'), ('person_add', '人物建档'), ('memory_add', '回忆添加'), ('photo_annotate', '照片补注'), ('review_pass', '审核通过'), ('vote_participate', '参与投票'), ('artifact_add', '物件建档'), ('artifact_annotate', '物件补注'), ('artifact_story', '物件故事补注'), ('artifact_dispute_resolve', '物件争议解决')], max_length=30, verbose_name='贡献类型'),
        ),
        migrations.AlterField(
            model_name='familyconfirmation',
            name='confirm_type',
            field=models.CharField(choices=[('person', '人物信息'), ('relation', '亲属关系'), ('photo_info', '照片信息'), ('photo_person', '照片人物'), ('memory', '回忆内容'), ('conflict', '冲突版本'), ('artifact', '物件信息'), ('artifact_dispute', '物件争议')], max_length=20, verbose_name='确认类型'),
        ),
        migrations.CreateModel(
            name='FamilyArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物件名称')),
                ('artifact_type', models.CharField(choices=[('old_object', '老物件'), ('letter', '家书'), ('ticket', '票证'), ('certificate', '奖状'), ('document', '证件'), ('manuscript', '手稿'), ('book', '书籍'), ('clothing', '服饰'), ('jewelry', '首饰'), ('furniture', '家具'), ('tool', '工具'), ('other', '其他')], default='other', max_length=30, verbose_name='物件类型')),
                ('artifact_no', models.CharField(blank=True, help_text='家庭内部编号', max_length=100, verbose_name='物件编号')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/', verbose_name='物件照片')),
                ('images', models.JSONField(blank=True, default=list, help_text='多视角照片列表', verbose_name='多图照片')),
                ('era', models.CharField(choices=[('1900s', '1900年代'), ('1910s', '1910年代'), ('1920s', '1920年代'), ('1930s', '1930年代'), ('1940s', '1940年代'), ('1950s', '1950年代'), ('1960s', '1960年代'), ('1970s', '1970年代'), ('1980s', '1980年代'), ('1990s', '1990年代'), ('2000s', '2000年代'), ('2010s', '2010年代'), ('2020s', '2020年代'), ('qing_dynasty', '清代'), ('republic', '民国'), ('unknown', '年代不详')], default='unknown', max_length=30, verbose_name='年代')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='具体年份')),
                ('year_unknown', models.BooleanField(default=False, verbose_name='年份未知')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='出土地/来源地')),
                ('location_detail', models.CharField(blank=True, max_length=500, verbose_name='详细地点')),
                ('material', models.CharField(blank=True, choices=[('paper', '纸质'), ('fabric', '织物'), ('metal', '金属'), ('wood', '木质'), ('ceramic', '陶瓷'), ('glass', '玻璃'), ('stone', '石质'), ('plastic', '塑料'), ('mixed', '混合材质'), ('other', '其他')], default='other', max_length=30, verbose_name='材质')),
                ('size', models.CharField(blank=True, help_text='如：长20cm宽15cm', max_length=200, verbose_name='尺寸')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='重量')),
                ('condition', models.CharField(blank=True, choices=[('excellent', '完好'), ('good', '较好'), ('fair', '一般'), ('poor', '较差'), ('damaged', '破损'), ('repaired', '已修复')], default='good', max_length=30, verbose_name='保存状况')),
                ('description', models.TextField(blank=True, help_text='外观、特征、印记等', verbose_name='物件描述')),
                ('story', models.TextField(blank=True, help_text='物件的来历和意义', verbose_name='背后故事')),
                ('story_completed', models.BooleanField(default=False, verbose_name='故事补注完成')),
                ('current_custodian', models.CharField(blank=True, max_length=100, verbose_name='当前保管人')),
                ('custodian_relation', models.CharField(blank=True, help_text='与家族的关系', max_length=100, verbose_name='保管人关系')),
                ('acquisition_method', models.CharField(blank=True, help_text='如：祖传、购买、赠送等', max_length=200, verbose_name='获取方式')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='获取日期')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('conflicted', '有争议'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='确认状态')),
                ('has_dispute', models.BooleanField(default=False, verbose_name='是否有争议')),
                ('dispute_count', models.IntegerField(default=0, verbose_name='争议次数')),
                ('created_by', models.CharField(default='家属', max_length=100, verbose_name='建档人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=100, verbose_name='最后更新人')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'db_table': 'family_artifact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artifact_type'], name='family_arti_artifac_ef845f_idx'), models.Index(fields=['era'], name='family_arti_era_7cbd83_idx'), models.Index(fields=['status'], name='family_arti_status_ac1312_idx'), models.Index(fields=['current_custodian'], name='family_arti_current_2bdd25_idx'), models.Index(fields=['location'], name='family_arti_locatio_37af6a_idx'), models.Index(fields=['name'], name='family_arti_name_b249d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtifactStorySupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='补注标题')),
                ('content', models.TextField(verbose_name='补注内容')),
                ('perspective', models.CharField(blank=True, help_text='如：使用经历、获得过程等', max_length=100, verbose_name='补注视角')),
                ('added_by', models.CharField(default='家属', max_length=100, verbose_name='补注人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='补注时间')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要故事')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_supplements', to='memories.familyartifact', verbose_name='物件')),
            ],
            options={
                'db_table': 'artifact_story_supplement',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('family_heirloom', '祖传'), ('purchase', '购买'), ('gift', '赠送'), ('found', '发现'), ('inheritance', '继承'), ('exchange', '交换'), ('reward', '奖励'), ('other', '其他')], default='family_heirloom', max_length=30, verbose_name='来源类型')),
                ('source_from', models.CharField(blank=True, max_length=200, verbose_name='来源人/出处')),
                ('source_place', models.CharField(blank=True, max_length=300, verbose_name='来源地点')),
                ('source_date', models.DateField(blank=True, null=True, verbose_name='来源日期')),
                ('source_year', models.IntegerField(blank=True, null=True, verbose_name='来源年份')),
                ('description', models.TextField(blank=True, verbose_name='来源说明')),
                ('witness', models.CharField(blank=True, max_length=200, verbose_name='见证人')),
                ('added_by', models.CharField(default='家属', max_length=100, verbose_name='记录人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主来源')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='memories.familyartifact', verbose_name='所属物件')),
            ],
            options={
                'db_table': 'artifact_source_record',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactDisputeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_field', models.CharField(choices=[('name', '物件名称'), ('type', '物件类型'), ('era', '年代'), ('year', '具体年份'), ('location', '地点'), ('source', '来源'), ('custodian', '保管人'), ('story', '背后故事'), ('description', '物件描述'), ('authenticity', '真伪'), ('ownership', '归属权'), ('other', '其他')], default='other', max_length=30, verbose_name='争议字段')),
                ('version_original', models.TextField(verbose_name='原版本（当前正式数据）')),
                ('version_original_author', models.CharField(default='', max_length=100, verbose_name='原版本提交人')),
                ('version_new', models.TextField(verbose_name='争议版本（新提交）')),
                ('version_new_author', models.CharField(default='', max_length=100, verbose_name='争议版本提交人')),
                ('description', models.TextField(blank=True, verbose_name='争议说明')),
                ('evidence', models.TextField(blank=True, verbose_name='证据说明')),
                ('status', models.CharField(choices=[('open', '待确认'), ('resolved', '已确认'), ('rejected', '已驳回'), ('merged', '已合并')], default='open', max_length=20, verbose_name='处理状态')),
                ('resolved_version', models.CharField(blank=True, choices=[('original', '原版本'), ('new', '新版本'), ('merged', '合并版本')], max_length=10, null=True, verbose_name='最终版本')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='确认人')),
                ('resolved_note', models.TextField(blank=True, verbose_name='确认说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='memories.familyartifact', verbose_name='关联物件')),
                ('related_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_disputes', to='memories.familyconfirmation')),
            ],
            options={
                'db_table': 'artifact_dispute_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactCustodianRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custodian_name', models.CharField(max_length=100, verbose_name='保管人姓名')),
                ('custodian_relation', models.CharField(blank=True, max_length=100, verbose_name='与家族关系')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始保管日期')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='开始保管年份')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束保管日期')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='结束保管年份')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前保管人')),
                ('custody_reason', models.CharField(blank=True, max_length=300, verbose_name='保管原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('added_by', models.CharField(default='家属', max_length=100, verbose_name='记录人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodian_records', to='memories.familyartifact', verbose_name='所属物件')),
            ],
            options={
                'db_table': 'artifact_custodian_record',
                'ordering': ['-is_current', 'start_year'],
            },
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='related_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='memories.familyartifact'),
        ),
        migrations.AddField(
            model_name='conflictversion',
            name='related_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_general', to='memories.familyartifact', verbose_name='关联物件'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='related_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='memories.familyartifact'),
        ),
        migrations.AddField(
            model_name='familyconfirmation',
            name='related_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='memories.familyartifact'),
        ),
        migrations.AddField(
            model_name='familyconfirmation',
            name='related_artifact_dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='memories.artifactdisputeversion'),
        ),
        migrations.CreateModel(
            name='ArtifactPhotoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_note', models.CharField(blank=True, help_text='如：照片中有此物件', max_length=300, verbose_name='关联说明')),
                ('added_by', models.CharField(default='家属', max_length=100, verbose_name='添加人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_photo_relations', to='memories.familyartifact', verbose_name='物件')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_relations', to='memories.photo', verbose_name='照片')),
            ],
            options={
                'db_table': 'artifact_photo_relation',
                'ordering': ['-created_at'],
                'unique_together': {('artifact', 'photo')},
            },
        ),
        migrations.CreateModel(
            name='ArtifactPersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('owner', '所有者'), ('user', '使用者'), ('maker', '制作者'), ('giver', '赠送者'), ('receiver', '接收者'), ('custodian', '保管人'), ('related', '关联人物'), ('other', '其他')], default='related', max_length=30, verbose_name='关系类型')),
                ('relation_note', models.CharField(blank=True, max_length=300, verbose_name='关系说明')),
                ('added_by', models.CharField(default='家属', max_length=100, verbose_name='添加人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_person_relations', to='memories.familyartifact', verbose_name='物件')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_relations', to='memories.person', verbose_name='人物')),
            ],
            options={
                'db_table': 'artifact_person_relation',
                'ordering': ['-created_at'],
                'unique_together': {('artifact', 'person', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='ArtifactMemoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_note', models.CharField(blank=True, max_length=300, verbose_name='关联说明')),
                ('added_by', models.CharField(default='家属', max_length=100, verbose_name='添加人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_memory_relations', to='memories.familyartifact', verbose_name='物件')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_relations', to='memories.memoryfragment', verbose_name='回忆')),
            ],
            options={
                'db_table': 'artifact_memory_relation',
                'ordering': ['-created_at'],
                'unique_together': {('artifact', 'memory')},
            },
        ),
        migrations.AddIndex(
            model_name='artifactdisputeversion',
            index=models.Index(fields=['artifact', 'status'], name='artifact_di_artifac_760034_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactdisputeversion',
            index=models.Index(fields=['dispute_field', 'status'], name='artifact_di_dispute_d17686_idx'),
        ),
    ]
